{{- if and .Values.synapseWorkers.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-synapse-federation-workers
  labels:
{{ include "matrix.labels" . | indent 4 }}
{{ include "matrix.synapseWorkers.labels" . | indent 4}}
spec:
  type: {{ .Values.synapseWorkers.service.type }}
  ports:
    - port: {{ .Values.synapseWorkers.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "matrix.synapseWorkers.federationWorkers" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
