{{- if .Values.riot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-riot-config
  labels:
{{ include "matrix.labels" . | nindent 4}}
{{ include "matrix.element.labels" . | indent 4}}
data:
  config.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": {{ include "matrix.baseUrl" . | quote }}
        }
        {{- if .Values.matrix.registration.identityServer -}}
        ,
        "m.identity_server": {
            "base_url": {{ .Values.matrix.registration.identityServer | quote }}
        }
        {{- end }}
      },
      "brand": {{ .Values.riot.branding.brand | quote }},
      "branding": {
        {{- if .Values.riot.branding.welcomeBackgroundUrl }}
        "welcomeBackgroundUrl": {{ .Values.riot.branding.welcomeBackgroundUrl | quote }},
        {{- end }}
        {{- if .Values.riot.branding.authHeaderLogoUrl }}
        "authHeaderLogoUrl": {{ .Values.riot.branding.authHeaderLogoUrl | quote }},
        {{- end }}
        {{- if .Values.riot.branding.authFooterLinks }}
        "authFooterLinks": {{ .Values.riot.branding.authFooterLinks | toJson }},
        {{- end }}
      },
      {{- if .Values.riot.integrations.enabled }}
      "integrations_ui_url": {{ .Values.riot.integrations.ui | quote }},
      "integrations_rest_url": {{ .Values.riot.integrations.api | quote }},
      "integrations_widgets_urls": {{ .Values.riot.integrations.widgets | toJson }},
      {{- end }}
      {{- if .Values.riot.labs }} {{/* if not empty */}}
      "showLabsSettings": true,
      {{- else }}
      "showLabsSettings": false,
      {{- end }}
      {{- if .Values.matrix.registration.allowGuests }} {{/* if not empty */}}
      "disable_guests": false,
      {{- else }}
      "disable_guests": true,
      {{- end }}
      "features": {
        {{- if .Values.riot.labs }}
        {{- range initial .Values.riot.labs }}
        {{ . | quote }}: "labs",
        {{- end }}
        {{ last .Values.riot.labs | quote }}: "labs"
        {{- end }}
      },
      "roomDirectory": {
        "servers": {{ .Values.riot.roomDirectoryServers | toJson }}
      },
      {{- if .Values.riot.welcomeUserId }}
      "welcomeUserId": {{ .Values.riot.welcomeUserId | quote }},
      {{- end }}
      "permalinkPrefix": {{ .Values.riot.permalinkPrefix | quote }}
    }
{{- end }}
