{{- if .Values.coturn.enabled }}
{{- $portRange := untilStep (int .Values.coturn.ports.from) (int (add1 .Values.coturn.ports.to)) 1 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-coturn
  labels:
{{ include "matrix.labels" . | indent 4 }}
{{ include "matrix.coturn.labels" . | indent 4}}
  {{- if .Values.coturn.service.annotations }}
  annotations:
    {{ include "matrix.coturn.service.annotations" . }}
  {{- end }}
spec:
  type: {{ .Values.coturn.service.type }}
  {{- if eq .Values.coturn.service.type "LoadBalancer" }}
  {{- if .Values.coturn.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.coturn.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.coturn.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:  {{ toYaml .Values.coturn.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: 3478
      targetPort: turn-3478
      {{- if eq .Values.coturn.service.type "NodePort" }}
      nodePort: 3478
      {{- end }}
      protocol: UDP
      name: turn-3478
    {{- range $portRange }}
    - port: {{ . }}
      targetPort: {{ . }}
      {{- if eq $.Values.coturn.service.type "NodePort" }}
      nodePort: {{ . }}
      {{- end }}
      protocol: UDP
      name: turn-{{ . }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-coturn
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
