{{- define "matrix-registration-config.yaml" }}
server_location: {{ include "matrix.baseUrl" . | squote }}
server_name: {{ .Values.matrix.serverName | squote }}
registration_shared_secret: {{ include "matrix.registration.sharedSecret" . | squote }} # see your synapse's homeserver.yaml
admin_api_shared_secret: {{ include "matrix.registrationApi.sharedSecret" . | squote }} # to generate tokens via the web api
base_url: '' # e.g. '/element' for https://example.tld/element/register
client_redirect: {{ .Values.matrixRegistration.clientRedirect | squote }}
client_logo: 'static/images/element-logo.png' # use '{cwd}' for current working directory
db: {{ .Values.matrixRegistration.connectionString | squote }}
host: '0.0.0.0'
port: 5000
rate_limit: ["100 per day", "10 per minute"]
allow_cors: false
ip_logging: false
logging:
  disable_existing_loggers: false
  version: 1
  root:
    level: DEBUG
    handlers: [console, file]
  formatters:
    brief:
      format: '%(name)s - %(levelname)s - %(message)s'
    precise:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: precise
      level: INFO
      filename: /data/m_reg.log
      maxBytes: 10485760 # 10MB
      backupCount: 3
      encoding: utf8
# password requirements
password:
  min_length: 8
{{- end }}
