{{- if .Values.matrixRegistration.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-matrix-registration
  labels:
{{ include "matrix.labels" . | nindent 4 }}
{{ include "matrix.matrixRegistration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.matrixRegistration.service.type }}
  ports:
    - port: {{ .Values.matrixRegistration.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-matrix-registration
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
