{{- if .Values.bots.maubot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-maubot-config
  labels:
{{ include "matrix.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ include "maubot-config.yaml" . | nindent 4 }}
{{- end }}
