{{- if .Values.bots.maubot.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "matrix.fullname" . }}-maubot-data
  labels:
{{ include "matrix.labels" . | nindent 4 }}
spec:
  {{- if .Values.bots.maubot.data.storageClass }}
  storageClassName: {{ .Values.bots.maubot.data.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bots.maubot.data.capacity }}
{{- end }}
