{{- if .Values.bots.maubot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-maubot
  labels:
{{ include "matrix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bots.maubot.service.type }}
  ports:
    - port: {{ .Values.bots.maubot.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-maubot
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
