{{- define "synapse_worker.yaml" }}
worker_app: {{ printf "\"{{ app }}\"" }}
worker_name: {{ printf "\"{{ name }}\"" }}

# The replication listener on the main synapse process.
worker_replication_host: "{{ include "matrix.fullname" . }}-synapse"

worker_listeners:
 - type: http
   port: {{ .Values.synapseWorkers.port }}
{{ printf "{% if listener_resources %}" }}
    resources:
      - names:
{{ printf "{%- for resource in listener_resources %}" }}
        - {{ printf "{{ resource }}" }}
{{ printf "{%- endfor %}" }}
{{ printf "{% endif %}" }}

worker_log_config: /data/{{ .Values.matrix.serverName }}.log.config
{{- end }}
