apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-synapse-worker-templates
  labels:
{{ include "matrix.labels" . | nindent 4}}
{{ include "matrix.synapseWorkers.labels" . | nindent 4}}
data:
  synapse_worker.yaml: |
    {{ include "synapse_worker.yaml" . | nindent 4 }}
{{ (.Files.Glob "synapse_worker_init/worker_init.py").AsConfig | indent 2 }}
