apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-synapse-worker-templates
  labels:
{{ include "matrix.labels" . | nindent 4}}
{{ include "matrix.synapseWorkers.labels" . | nindent 4}}
data:
{{ (.Files.Glob "synapse_worker_init/*").AsConfig | indent 2 }}
